repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer

  - repo: https://github.com/omnilib/ufmt
    rev: 1.3.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 21.12b0
          - usort == 1.0.0

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
